---
title: "py-exceptiongroup"
layout: cache
categories: [package, develop-2024-11-10]
meta: {"versions": ["1.1.1"], "compilers": ["gcc@=11.1.0", "gcc@=11.4.0"], "oss": ["ubuntu20.04", "ubuntu22.04"], "platforms": ["linux"], "targets": ["x86_64_v3"], "stacks": ["data-vis-sdk", "e4s", "root"], "num_specs": 2, "num_specs_by_stack": {"root": 2, "data-vis-sdk": 1, "e4s": 1}}
spec_details: [{"hash": "vdbsfyq5skbvykbvni5ltnrthdnqi7go", "compiler": "gcc@=11.1.0", "versions": ["1.1.1"], "os": "ubuntu20.04", "platform": "linux", "target": "x86_64_v3", "variants": ["build_system=python_pip"], "stacks": ["root", "data-vis-sdk"], "size": "-", "tarball": "https://binaries.spack.io/develop-2024-11-10/build_cache/linux-ubuntu20.04-x86_64_v3/gcc-11.1.0/py-exceptiongroup-1.1.1/linux-ubuntu20.04-x86_64_v3-gcc-11.1.0-py-exceptiongroup-1.1.1-vdbsfyq5skbvykbvni5ltnrthdnqi7go.spack"}, {"hash": "wq7mskrpzzoffsbrav72dkw2c5ggadwu", "compiler": "gcc@=11.4.0", "versions": ["1.1.1"], "os": "ubuntu22.04", "platform": "linux", "target": "x86_64_v3", "variants": ["build_system=python_pip"], "stacks": ["e4s", "root"], "size": "-", "tarball": "https://binaries.spack.io/develop-2024-11-10/build_cache/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/py-exceptiongroup-1.1.1/linux-ubuntu22.04-x86_64_v3-gcc-11.4.0-py-exceptiongroup-1.1.1-wq7mskrpzzoffsbrav72dkw2c5ggadwu.spack"}]
---